# theme: jekyll-theme-slate
title: Kailin Huang's homepage

# plugins:
# - jekyll-relative-links
# relative_links:
#   enabled: true
#   collections: true
# include:
#   - README.md
#   - index.md

logo: /resources/KailinHuangPhoto.jpg
cv: /resources/CV-Kailin_Huang-2019_Mar_Photo.pdf
MT_PDF: /resources/MT_ObjSLAM_LaTeX.pdf
description: Kailin Huang's homepage

theme: jekyll-theme-minimal