# theme: jekyll-theme-slate
title: Kailin Huang's homepage

# plugins:
# - jekyll-relative-links
# relative_links:
#   enabled: true
#   collections: true
# include:
#   - README.md
#   - index.md

logo: /resources/Kailin2023.jpg
# cv: /resources/CV-Kailin_Huang-2023_July
MT_PDF: /resources/MT_ObjSLAM_LaTeX.pdf
description:
google_analytics: UA-136368704-1

theme: jekyll-theme-minimal
