# theme: jekyll-theme-slate
title: Kailin Huang's homepage

plugins:
# - jekyll-relative-links
# relative_links:
#   enabled: true
#   collections: true
include:
  - README.md
  - index.md

logo: /assets/img/logo.png
description: Kailin Huang's homepage

theme: jekyll-theme-minimal