# theme: jekyll-theme-slate
title: Kailin Huang's homepage (Currently under construction)

plugins:
- jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - index.md

theme: jekyll-theme-minimal